# Generated by Django 6.1 on 2026-08-17 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_text', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField()),
                ('current_location_lng', models.FloatField()),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField()),
                ('pickup_location_lng', models.FloatField()),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField()),
                ('dropoff_location_lng', models.FloatField()),
                ('cycle_used_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('log_date', models.DateField()),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_miles_today', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recap_a_last_7_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recap_b_available_tomorrow', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recap_c_last_8_days_if_restart', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('segments', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'day_index'), name='unique_trip_day_index')],
            },
        ),
    ]
