# Generated by Django 6.1 on 2026-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='transitions',
            field=models.JSONField(default=list),
        ),
    ]
