# Generated by Django 6.1 on 2026-08-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_dailylog_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
